v4l2:
  device_path: /dev/video2
  width: 1920
  height: 1080
  framerate: 60.0
  pixel_format: yuyv
  invert_image: false

debug:
  show_window: true
  draw_overlay: true

inference:
  backend: bright_spot
  model_path: ""
